# Generated by Django 3.0.14 on 2023-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.CharField(default=90, max_length=5),
        ),
    ]
