# Generated by Django 3.0.14 on 2023-02-12 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20230212_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseproject',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.Project'),
        ),
    ]
