# Generated by Django 3.2.4 on 2024-05-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20230212_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('current', 'Актуально'), ('not_current', 'Не актуально')], max_length=50)),
            ],
        ),
    ]
