# Generated by Django 5.2.14 on 2026-05-30 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_volunteerproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerProject',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='responseproject',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('current', 'Актуально'), ('not_current', 'Не актуально')], default='current', max_length=50),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.project'),
        ),
    ]
