# Generated by Django 5.2.14 on 2026-06-21 15:03

from django.db import migrations, models


def infer_attendance_status(apps, schema_editor):
    ResponseProject = apps.get_model('organization', 'ResponseProject')
    ResponseProject.objects.filter(rating__lt=0).update(attendance_status='missed')
    ResponseProject.objects.filter(rating__gt=0).update(attendance_status='attended')


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_responseproject_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseproject',
            name='attendance_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Күтілуде'),
                    ('attended', 'Қатысты'),
                    ('missed', 'Қатыспады'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.RunPython(infer_attendance_status, migrations.RunPython.noop),
    ]
