# Generated by Django 3.0.14 on 2023-02-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230209_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='content',
        ),
    ]
