# Generated by Django 5.2.14 on 2026-06-21 16:13

from django.db import migrations, models


def create_default_home_statistic(apps, schema_editor):
    HomeStatistic = apps.get_model('main', 'HomeStatistic')
    HomeStatistic.objects.get_or_create(id=1)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_support_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_volunteers_value', models.CharField(default='1,500+', max_length=30)),
                ('active_volunteers_label', models.CharField(default='Белсенді волонтерлер', max_length=100)),
                ('completed_projects_value', models.CharField(default='350+', max_length=30)),
                ('completed_projects_label', models.CharField(default='Аяқталған жобалар', max_length=100)),
            ],
            options={
                'verbose_name': 'Главная статистика',
                'verbose_name_plural': 'Главная статистика',
            },
        ),
        migrations.RunPython(create_default_home_statistic, migrations.RunPython.noop),
    ]
