# Generated by Django 5.2.14 on 2026-06-21 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homestatistic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersupport',
            options={'verbose_name': 'Ответ на обращение', 'verbose_name_plural': 'Ответы на обращения'},
        ),
        migrations.AlterModelOptions(
            name='homestatistic',
            options={'verbose_name': 'Статистика главной страницы', 'verbose_name_plural': 'Статистика главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterField(
            model_name='answersupport',
            name='content',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answersupport',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='answersupport',
            name='support',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.support', verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='homestatistic',
            name='active_volunteers_label',
            field=models.CharField(default='Белсенді волонтерлер', max_length=100, verbose_name='Подпись активных волонтеров'),
        ),
        migrations.AlterField(
            model_name='homestatistic',
            name='active_volunteers_value',
            field=models.CharField(default='1,500+', max_length=30, verbose_name='Число активных волонтеров'),
        ),
        migrations.AlterField(
            model_name='homestatistic',
            name='completed_projects_label',
            field=models.CharField(default='Аяқталған жобалар', max_length=100, verbose_name='Подпись завершенных проектов'),
        ),
        migrations.AlterField(
            model_name='homestatistic',
            name='completed_projects_value',
            field=models.CharField(default='350+', max_length=30, verbose_name='Число завершенных проектов'),
        ),
        migrations.AlterField(
            model_name='support',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Тема обращения'),
        ),
        migrations.AlterField(
            model_name='support',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
